### ISSUE TITLE
JSONDecodeError("Expecting value", s, err.value) from None

### ISSUE THREAD

**Issue by robotzheng** [sail-sg/CPO#2]
python clean_dataset.py

Traceback (most recent call last):
  File "/home/notebook/code/personal/80306170/AGI/LAM/AgentQ/CPO/clean_dataset.py", line 21, in <module>
    instances = json.loads(f.read())
  File "/opt/conda/envs/EN_VLLM/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/envs/EN_VLLM/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/envs/EN_VLLM/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jadeCurl** [comment]
Hi,

Please check whether the format of your JSON file is correct.
